development:
  adapter: mysql2
  encoding: utf8
  database: ntpumis_be
  host: localhost
  username: root
  password: ntpumis2015

test:
  adapter: mysql2
  encoding: utf8
  database: ntpumis_development
  host: localhost
  username: root
  password: ntpumis2015

production:
  adapter: mysql2
  encoding: utf8
  database: ntpumis_be
  host: localhost
  username: root
  password: ntpumis2015
