development:
  adapter: mysql2
  encoding: utf8
  database: ntpumis_be
  host: localhost
  username: root
  password: root

test:
  adapter: mysql2
  encoding: utf8
  database: ntpumis_development
  host: localhost
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  database: ntpumis_be
  host: localhost
  username: root
  password: root
